package com.smartlog.analyzer.detector;

import com.smartlog.analyzer.model.LogEntry;
import com.smartlog.analyzer.model.SecurityAlert;

import java.util.List;

/**
 * Common contract for all heuristic and signature-based threat detection modules.
 */
public interface ThreatDetector {

    /**
     * Consumes an individual normalized log event and updates detection state.
     *
     * @param entry the parsed log entry
     */
    void process(LogEntry entry);

    /**
     * Signals that the stream of log entries has finished, allowing stateful detectors
     * to finalize sliding windows and generate aggregated alerts.
     */
    void finish();

    /**
     * Returns the list of security alerts generated by this detector.
     */
    List<SecurityAlert> getAlerts();

    /**
     * Resets detector state for re-runs.
     */
    void reset();

    /**
     * Friendly name of the detection module.
     */
    String getName();
}
